# Generated by Django 5.0.1 on 2024-01-22 14:49

import user_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name=user_app.models.FilePathGenerator()),
        ),
    ]
