# Generated by Django 5.0.1 on 2024-01-22 14:49

import django.db.models.deletion
import house_app.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_app', '0002_alter_userprofile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=225)),
                ('picture', models.FileField(blank=True, null=True, upload_to=house_app.models.FilePathGenerator())),
                ('description', models.TextField()),
                ('points', models.IntegerField(default=0)),
                ('task_completed_count', models.IntegerField(default=0)),
                ('task_uncompleted_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manager', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='house_manager', to='user_app.userprofile')),
            ],
        ),
    ]
